package by.htp.rental.builder;

public enum EquipmentTagName {
	MATERIAL, CATEGORY, CATEGORIES, TERM_OF_SERVICE, PRICE, 
	WEIGHT, WIDTH, HEIGHT, PERSON_CATEGORY, COUNT_SPEED_MODE, 
	SIZE, MODEL,
	HELMET, SKATE, BYCICLE, EQUIPMENTS 
}
